### ISSUE TITLE
Make Lisk Elements a monorepo

### ISSUE THREAD

**Issue by Tosch110** [LiskHQ/lisk-elements#418]
Create a monorepo using lerna, resulting in several npm packages that can be installed seperately.

Aimed for Lisk-JS 1.1

**Comment by alepop** [comment]
@Tosch110 `lisk-js` will be split into a bunch of packages? why use monorepo for a small library?

**Comment by willclarktech** [comment]
@alepop 
The reasoning is that the functionality in the various source modules (`api`, `constants`, `crypto`, `transactions`) are pretty distinct (or should be). Splitting them into separate packages will allow projects (e.g. going forward sidechain applications) to be more selective about which parts they want. We'll probably still provide a package which bundles them all together in case somebody needs everything.

Why a monorepo? It simplifies various things:
- less restructuring required for the migration
- synchronising release schedules
- common dependency management
- easier to see cross-dependency relationships
- easier to share common resources such as (upcoming) flow types

**Comment by alepop** [comment]
@willclarktech I understood your point about using only necessary parts of `liks-js.` agree with it 👍 I had tried to use `lerna` in my project. Seems simple and straightforward.

**Comment by willclarktech** [comment]
Yeah, I'm aware of at least one circular dependency we'll have to deal with, but the hope is that the process will lead to us placing code in more logical locations because of it. I'd be interested to hear more about the issues that arose with types?

**Comment by willclarktech** [comment]
Also errors maybe?

**Comment by willclarktech** [comment]
Remaining issues will be opened separately. E.g. Jenkins.
