### ISSUE TITLE
Apply a consistent approach to function parameters

### ISSUE THREAD

**Issue by Tosch110** [LiskHQ/lisk-elements#605]
Function now take parameters sometimes as object, sometimes in order.
We should be more consistent and use objects straight away.

### Description

Take objects as parameters is very useful in ES6, for destructuring patterns and also as overview, we should be consistent here.

**Expected behavior:** 

Always use objects

**Actual behavior:** 

Sometimes using objects, sometimes parameters in the correct order

### Versions

1.0.0

**Comment by shuse2** [comment]
I think inputs that are required should be in parameters.
Also, I dont think it make sense for 1 or 2 inputs (like number, string) to be an object
Object destructuring is useful, but I don't think it fits for everything

**Comment by Tosch110** [comment]
I understand your point. Though I was sitting on an integration and had to look up which pattern to use all the time. I would appreciate it to be as consistent as possible. I think having objects even for 1 or 2 inputs when people get used to it. I am not aware of any downsides that it could create. Do you have something in mind?

**Comment by shuse2** [comment]
I think downsides are
- more code for simple stuff
- you need to know exactly what is the name of input is.
Also, I don't think that is a pattern widely used.
```
convertToTimeString('2017-11-10 12:20:00');
convertToTimeString({ time: '2017-11-10 12:20:00'});
----
getNextNumber({ number: 1})
getNextNumber(1)
```

**Comment by willclarktech** [comment]
Seems like there's potentially an important difference between 1 input and 2+ inputs here.

**Comment by Tosch110** [comment]
Yes, I agree to will. We should draw a line depending on how many arguments are taken. I actually like 2+

**Comment by shuse2** [comment]
I think it's hard to draw a line. 
Object is useful when it's not required and name is obvious enough to be provided.
```
add(1, 20)
add({ first: 1, target: 20})
```

**Comment by willclarktech** [comment]
Issue renamed for generality. Planned for 2.0.0.
