### ISSUE TITLE
Revisit cryptography module initialisation

### ISSUE THREAD

**Issue by willclarktech** [LiskHQ/lisk-elements#667]
**Expected behavior:** The cryptography module's functionality should not be subject to race conditions. We should either have no dependencies on libraries which initialise asynchronously, or we should export a module which itself initialises asynchronously (when the dependencies are ready).

**Actual behavior:** We use js-nacl, which initialises asynchronously, but we don't wait for the initialisation to complete before exporting the cryptography functions.

Related to #435 

### Versions

1.0.0

**Comment by webmaster128** [comment]
Given that WebAssembly compilation is asynchronous, I strongly recommend to provide asynchronous APIs. Switching to an up-to-date libsodium.js will also require this.

**Comment by willclarktech** [comment]
To be completed after #435

**Comment by willclarktech** [comment]
Not necessary after #687
