### ISSUE TITLE
Invalid test value for amount

### ISSUE THREAD

**Issue by webmaster128** [LiskHQ/lisk-elements#669]
In https://github.com/LiskHQ/lisk-elements/blob/2f57fa8/test/transactions/utils/get_transaction_bytes.js the test value `const defaultAmount = (3 + 2 ** 62).toString();` is used. One might expect this to be 3+2^62 = 4611686018427387907 but due to the nature of JavaScript numbers, the result is 4611686018427388000.

The most concerning part here is that the expected test value is also wrong, so it seems like the test data was created using the same tooling as the implementation. Instead of the correct "0300000000000040" the expected value is "6000000000000040".

To create the proper hex value, you can use `python3 -c 'print(hex(2**62+3))'` and reverse the order of the bytes.

**Comment by willclarktech** [comment]
This value was added as part of a fix for a bug in a previous (unreleased) form of Lisk Elements v1.0.0. The salient issue at the time was whether the function was allocating enough bytes for the amount value, which the tests as they are successfully establish. However, I agree that as written this is misleading (e.g. the `3+` looks like it's doing something but makes no difference), and a better test would also ensure that we're handling large numbers properly in JS (which in fact we are).

PRs welcome!
