### ISSUE TITLE
Replace API client to enable usage from react-native

### ISSUE THREAD

**Issue by shuse2** [LiskHQ/lisk-elements#670]
### Description

Current popsicle seems not to support `react-native`.
We should replace with some library that supports `node.js`, `browsers` and `react-native`.

Possible library
- https://github.com/lquixada/cross-fetch
- https://github.com/axios/axios

**Comment by tobiaslins** [comment]
Hi @shuse2 ,
How was this decision made? 
Why cross-fetch > axios?
What's about frisbee https://github.com/niftylettuce/frisbee ?

THanks :)

**Comment by shuse2** [comment]
@tobiaslins 
@reyraa was trying out axios on RN, and it wasn't working well.
Also, there was no official support for RN by axios, so we decided to use cross-fetch.

**Comment by tobiaslins** [comment]
https://facebook.github.io/react-native/docs/network.html#using-other-networking-libraries

axios and frisbee are in their offical documentation!

I also have 2 RN apps running for a while and using axios there since months

But it's ok for now, just wanted to know why

**Comment by shuse2** [comment]
Ah yes! thank you for the information.
I remember now why I used axios for my RN apps before =p

Im having a problem to write test using `cross-fetch`, so I might re-consider.

**Comment by shuse2** [comment]
so I had struggle with the test with `cross-fetch`, so I changed with `axios` =)
