### ISSUE TITLE
Inconsistency in encryptAES256GCMWithPassword

### ISSUE THREAD

**Issue by 5an1ty** [LiskHQ/lisk-elements#685]
```
const encryptAES256GCMWithPassword = (plainText, password, iterations) => {
	const iv = crypto.randomBytes(12);
	const salt = crypto.randomBytes(16);
	const key = getKeyFromPassword(password, salt, iterations);

	const cipher = crypto.createCipheriv('aes-256-gcm', key, iv);
	const firstBlock = cipher.update(plainText, 'utf8');
	const encrypted = Buffer.concat([firstBlock, cipher.final()]);
	const tag = cipher.getAuthTag();

	return {
		iterations: iterations || null,
		cipherText: encrypted.toString('hex'),
		iv: iv.toString('hex'),
		salt: salt.toString('hex'),
		tag: tag.toString('hex'),
		version: ENCRYPTION_VERSION,
	};
};
```

```
const getKeyFromPassword = (password, salt, iterations) =>
	crypto.pbkdf2Sync(
		password,
		salt,
		iterations || PBKDF2_ITERATIONS,
		PBKDF2_KEYLEN,
		PBKDF2_HASH_FUNCTION,
	);
```

getKeyFromPassword seems to have a sane default for iterations in PBKDF2_ITERATIONS but encryptAES256GCMWithPassword defaults iterations to null

**Comment by willclarktech** [comment]
If `iterations` is not explicitly passed to `encryptAES256GCMWithPassword`, it gets the value `undefined`, which is passed to `getKeyFromPassword`, so the default of `PBKDF2_ITERATIONS` is used. Have I misunderstood your issue?

**Comment by 5an1ty** [comment]
Yes, getKeyFromPassword works as intended, but encryptAES256GCMWithPassword return value will contain null for the iterations property.

```
return {
		iterations: iterations || null,
```

**Comment by willclarktech** [comment]
Gotcha, thanks for the report.

**Comment by willclarktech** [comment]
Ah I see what you mean. When we stringify that, `null` means the iterations are left out entirely: https://github.com/LiskHQ/lisk-elements/blob/development/src/cryptography/convert.js#L73-L87

**Comment by willclarktech** [comment]
@5an1ty OK to close?

**Comment by 5an1ty** [comment]
Ok to close, thank you for clarifying.

**Comment by willclarktech** [comment]
Changing the default iterations value of the output of `encryptAES256GCMWithPassword` from `null` to `PBKDF2_ITERATIONS` will take 2 seconds and be more future-proof.
