### ISSUE TITLE
Refused to set unsafe header “User-Agent” in axios

### ISSUE THREAD

**Issue by yasharAyari** [LiskHQ/lisk-elements#696]
### Description

I used `lisk-elements` in `lisk-hub`. Everything works as expected but there is an error in the browser console. I think xhr lib in `axois` causes this error.

**Expected behavior:** there must be no error in browser console because of `lisk-elements` 

**Actual behavior:** it keeps showing this error
`Refused to set unsafe header “User-Agent”`

**Comment by willclarktech** [comment]
Closed in #712
