### ISSUE TITLE
Fix brittle performance-based tests

### ISSUE THREAD

**Issue by willclarktech** [LiskHQ/lisk-elements#702]
**Expected behavior:** Tests should pass or fail consistently on CI.

**Actual behavior:** The cryptography tests concerned with how much time password-based key derivation takes fail non-deterministically on CI. We should broaden the range of acceptable behaviour.

### Versions

1.0.0

**Comment by yatki** [comment]
Issue is related to server performance. We need a node with better configuration. No action is needed on codebase. (However, would be good to disable cypress video creation)

**Comment by willclarktech** [comment]
@yatki Please open an issue about disabling video creation.
