### ISSUE TITLE
Android doesn't behave with instances of Buffer like instances of Array

### ISSUE THREAD

**Issue by reyraa** [LiskHQ/lisk-elements#710]
### Expected behavior
Lisk Element should work in Android environment seamlessly.

### Actual behavior
Since the variables of type Buffer are not instances of Array, they don't have methods like `reverse` or `slice`. Major browsers add these methods to the interface by default but this is not the case for Android. 
The same issue has been brought up in [some other projects](https://github.com/Airbitz/react-native-fast-crypto/issues/4) too.

### Steps to reproduce
Try running Lisk element in a simple RN application in the Android environment. it should throw errors similar to this
![screenshot_1531237325](https://user-images.githubusercontent.com/666685/42521700-c4d509ac-8469-11e8-82fd-857fc9c7339e.png)

### Which version(s) does this affect? (Environment, OS, etc...)
OS: Android
Environment: React Native
Version:

**Comment by willclarktech** [comment]
@reyraa Since this is very environment specific, is it an option for you to polyfill the required methods yourself for RN in Android? E.g. along the lines of the comment here: https://github.com/Airbitz/react-native-fast-crypto/issues/6#issuecomment-358153378

**Comment by reyraa** [comment]
I can fix the issue using such a hack, but then either we have to add this to the documentation of Lisk Element, or let all the people spent their time to find the hack. but I believe it's helpful if Lisk Element works in all major environments seamlessly.
Running methods of the Array interface on instances of Buffer can't be correct. Although major browsers provide the polyfill, we're still using a non-native method. 

As another solution, I found some [polyfills](https://github.com/crypto-browserify/buffer-reverse) which can fix this issue.

**Comment by willclarktech** [comment]
Current status: we're hoping that https://github.com/feross/buffer/ can be used. @reyraa will try overriding the global `Buffer` unconditionally (instead of conditionally as is the default when using `create-react-app`).

**Comment by willclarktech** [comment]
Update: that won't work because the library doesn't aim to cover methods specific to `Uint8Array`.

https://github.com/feross/buffer/issues/167

**Comment by willclarktech** [comment]
We should be able to use this: https://github.com/substack/typedarray
