### ISSUE TITLE
1.0.0-rc.0 not installing via NPM on Windows 10

### ISSUE THREAD

**Issue by kilkelly** [LiskHQ/lisk-elements#724]
### Expected behavior
lisk-elements@1.0.0-rc.0 installs via NPM successfully on Windows 10.

### Actual behavior
Installation of lisk-elements@1.0.0-rc.0 fails during installation via NPM on Windows 10. The following error code is shown:

```
> lisk-elements@1.0.0-rc.0 postinstall C:\projectdirectory\node_modules\lisk-elements
> if [ ! -f ./dist-node/index.js ]; then npm run build; fi

! was unexpected at this time.
...
npm ERR! Failed at the lisk-elements@1.0.0-rc.0 postinstall script.
```

### Steps to reproduce
`npm i --save lisk-elements@1.0.0-rc.0`

(I did try `npm i --save lisk-elements` but it installed version 0.0.0)

### Which version(s) does this affect? (Environment, OS, etc...)
OS: Windows 10 Home
Node: v8.11.1
NPM: v5.8.0

**Comment by willclarktech** [comment]
Thanks for the report! Related to https://github.com/LiskHQ/lisk-elements/issues/686

**Comment by kilkelly** [comment]
No worries, thanks for the fast reply.

**Comment by willclarktech** [comment]
@yatki will look into this. Worst case scenario we can remove the `postinstall` script entirely and add a note to the README for GitHub installers.
