### ISSUE TITLE
The CDN scripts are down

### ISSUE THREAD

**Issue by BlueDragon555** [LiskHQ/lisk-elements#740]
I was using vanilla JS and noticed the CDN scripts are down, they currently and give an access denied error when visiting them.

**Comment by BlueDragon555** [comment]
The suggested includes from the readme:

<script src="https://js.lisk.io/lisk-elements-1.0.0.js"></script>
<script src="https://js.lisk.io/lisk-elements-1.0.0.min.js"></script>

**Comment by willclarktech** [comment]
@BlueDragon555 Those links are from the `development` branch. Version 1.0.0 hasn't been released yet. If you want to try the release candidate you can use. `https://js.lisk.io/lisk-elements-1.0.0-rc.0.js` (or the same with `.min.js`).

**Comment by BlueDragon555** [comment]
Thanks

**Comment by willclarktech** [comment]
OK to close?

**Comment by BlueDragon555** [comment]
Sure yeah

**Comment by willclarktech** [comment]
This issue relates to our longstanding debate over whether the default branch should be `master` or `development`.
