### ISSUE TITLE
Browser tests should fail if browser test files have not been built

### ISSUE THREAD

**Issue by willclarktech** [LiskHQ/lisk-elements#750]
### Expected behavior

If the files required for running browser tests have not been built, the tests should fail.

### Actual behavior

They pass even though everything 404s.

### Steps to reproduce

Remove the browsertest build. Start the browsertest server. Run the browsertests. They should exit with success very quickly.

### Which version(s) does this affect? (Environment, OS, etc...)

1.0.0+

**Comment by yatki** [comment]
@willclarktech I couldn't reproduce the issue. Can you try to recreate issue and be a bit more specific.

**Comment by willclarktech** [comment]
@yatki Also couldn't reproduce, sorry for the confusion. I suspect I had an issue on the `1.0.0` branch but if this is cleared up on `1.1.0` anyway, no need to worry.
