### ISSUE TITLE
Update maximum numbers defined in constants

### ISSUE THREAD

**Issue by shuse2** [LiskHQ/lisk-elements#763]
### Description
While `18446744073709551615` is correct maximum unsigned 64bit integer, but in lisk-core, it uses `postgres` which does not support unsigned Bigint.
Therefore, for validation for values that are stored as `number` in core, should be checked against signed 64bit int maximum, `9223372036854775807 `.

**Comment by willclarktech** [comment]
@shuse2 Does this need to go into v1.0.0?

**Comment by shuse2** [comment]
yes it should go into 1.0

**Comment by shuse2** [comment]
It's actually checking the `totalamount` constant.
https://github.com/LiskHQ/lisk/blob/development/logic/transaction.js#L639
so it should comply with this

**Comment by willclarktech** [comment]
@shuse2 Do we also need to adjust the `MAX_ADDRESS_NUMBER` and `MAX_TRANSACTION_ID` because of the Postgres limit?

**Comment by shuse2** [comment]
address and transaction id are saved as string, varchar. so i think it's fine there

**Comment by willclarktech** [comment]
Closed in #765
