### ISSUE TITLE
Support for Raw Transactions (for Hardware Wallets Integration)

### ISSUE THREAD

**Issue by hirishh** [LiskHQ/lisk-elements#768]
### Expected behavior
Lisk-Elements should provide a passphrase-free API in order to create Raw transactions (not-signed) that can be used with Hardware Wallets (Ledger, Trezor).

### Actual behavior
Lisk-Elements provides only API where passphrase is mandatory in order to sign the transaction

### Steps to reproduce
None

### Which version(s) does this affect? (Environment, OS, etc...)
All

**Comment by alepop** [comment]
@hirishh you can already create raw transaction if you don't pass a passphrase to a transaction builder function https://github.com/LiskHQ/lisk-elements/blob/e6db330fc8e9e70da32465699a328da08b0efb8f/src/transactions/utils/wrap_transaction_creator.js#L22

**Comment by hirishh** [comment]
Yep you're right, I missed that.

Thank you!
