### ISSUE TITLE
Benchmark tweetnacl vs sodium-native

### ISSUE THREAD

**Issue by ManuGowda** [LiskHQ/lisk-elements#789]
### Expected behavior
The benchmark statistics will allow users to choose `tweentnacl` or `sodium-native` or any other library in the future.
Following are the use cases that we consider to benchmark:
- [ ] Keys generation
- [ ] Create transaction
- [ ] Sign transaction
- [ ] Verify transaction

### Actual behavior
Currently, we do not have any benchmark to evaluate the performance of `tweentnacl` or `sodium-native`.

**Comment by willclarktech** [comment]
@ManuGowda Also consider
- [ ] Get random bytes (different lengths)
- [ ] Crypto box
- [ ] Crypto box open

By `Create transaction` do you mean `create and sign`?

**Comment by ManuGowda** [comment]
@willclarktech yes create and sign the transaction.
