### ISSUE TITLE
new crypto method "getAddressFromPrivateKey"

### ISSUE THREAD

**Issue by roccomuso** [LiskHQ/lisk-elements#952]
I saw cryptography module always assume the use of a passphrase to get the keys.

Is there a way through the `cryptography` module to craft a `getAddressFromPrivateKey` method?
and so the get a public or address from a privateKey instead of a passphrase?

I used this at the moment `nacl.sign.keyPair.fromSecretKey(Buffer.from(privKey, 'hex'))`

**Comment by MaciejBaj** [comment]
```getAddressFromPublicKey(

**Comment by mitsujutsu** [comment]
We currently don't have functionality in `cryptography` module to support this feature, however we will include it in 2.1 release. For the time being I would recommend the `nacl` function you are already utilizing.
